"""Blueprint for routes to run and access the PIE colony recognotion workflow
application.
"""

import os

from flask import Blueprint, jsonify, make_response, request, send_file

from flowserv.app import flowapp

import flowserv.config.api as config
import flowserv.util as util
import flowserv.error as err


bp = Blueprint('files', __name__, url_prefix='/files')


@bp.route('/workflow/<string:workflow_id>/runs/<string:run_id>/files/<string:file_id>')  # noqa: E501
def download_result_file(workflow_id, run_id, file_id):
    """Download a resource file that was generated by a successful workflow
    run.

    Parameters
    ----------
    workflow_id: string
        Unique workflow identifier.
    run_id: string
        Unique run identifier
    file_id: string
        Unique resource file identifier

    Returns
    -------
    flask.response_class

    Raises
    ------
    flowserv.error.UnauthenticatedAccessError
    flowserv.error.UnauthorizedAccessError
    flowserv.error.UnknownWorkflowGroupError
    """
    workflow = flowapp(identifier=workflow_id)
    file, name, mime_type = workflow.get_file(run_id=run_id, file_id=file_id)
    return send_file(
        file,
        as_attachment=True,
        attachment_filename=name,
        mimetype=mime_type
    )


@bp.route(
    '/runs/<string:run_id>/files/uploads/<string:file_id>',
    methods=['GET']
)
def download_input_file(run_id, file_id):
    """Download a given file that was perviously uploaded for a workflow.

    NOTE: At this point, the user is not authenticated for file downloads to
    allow download in the GUI via browser redirect.

    Parameters
    ----------
    run_id: string
        Unique run identifier
    file_id: string
        Unique file identifier

    Returns
    -------
    flask.response_class

    Raises
    ------
    flowserv.error.UnauthenticatedAccessError
    flowserv.error.UnauthorizedAccessError
    flowserv.error.UnknownFileError
    """
    with service() as api:
        fh, file = api.uploads().get_file(
            group_id=run_id,
            file_id=file_id
        )
        return send_file(
            file,
            as_attachment=True,
            attachment_filename=fh.name,
            mimetype=fh.mime_type
        )
